- name: shell operation
  shell: |
  sudosed -i "s/\(KUBELET_EXTRA_ARGS=\).*/\1--node-ip={{ hostvars[groups['workers'][0]].ansible_host }}/" /etc/sysconfig/kubelet

  sudokubeadm join {{ hostvars[groups['master'][0]].ansible_host }}:6443 --token tqqm17.dq8rsbk5k8tps07y

  sudo kubectl patch node worker --patch='{"metadata": {"labels": {"node-role.kubernetes.io/node": ""}}}'
