- hosts: localhost

  pre_tasks:
  - name: Start Docker Container
    docker_container:
      name: "centos-{{ item }}"
      state: started
      image: sbeliakou/ansible-training:centos
      privileged: true
    with_sequence: count=2
    register: centos
    become: yes

  - name: Compose In-Memory Inventory
    add_host:
      name: "{{ container.NetworkSettings.IPAddress }}"
      ansible_host: "{{ container.Name }}"
      ansible_connection: docker
      groups:
      - webservers
    loop: "[{{ centos.results[0] }}]"
    loop_control:
      label: "{{ container.Name }}"
    vars:
      container: "{{ item.ansible_facts.docker_container }}"

  - name: Compose In-Memory Inventory
    add_host:
      name: "{{ container.NetworkSettings.IPAddress }}"
      ansible_host: "{{ container.Name }}"
      ansible_connection: docker
      groups:
      - appservers
    loop: "{{ centos.results[1:] }}"
    loop_control:
      label: "{{ container.Name }}"
    vars:
      container: "{{ item.ansible_facts.docker_container }}"

# --- docker destroy containers  
#  post_tasks:
#  - name: Destroy VM
#    docker_container:
#      name: "{{ hostvars[item].ansible_host[0:] }}"
#      state: absent
#    loop: "{{ groups['webservers'] + groups['appservers'] }}"

- hosts: all
  roles:
    - role: user
      user_name: devops
      user_group2: vagrant