- name: Provison Users
  hosts: all
  vars:
    usr: devops


  tasks:
  - name: Create Group
    group:
      name: "{{ usr }}"
      state: present

  - name: Create Users
    user:
      name: "{{ usr }}"
      groups: "{{ usr }}"
      shell: /bin/bash
      state: present

  - name: SSH Access
    authorized_key:
      user: "{{ usr }}"
      state: present
      key: "{{ lookup('file', 'files/' + usr + '.key.pub') }}"

  - name: Copy new file to "sudoers.d"
    copy:
      src: files/devops
      dest: /etc/sudoers.d/devops
      backup: yes
      validate: /usr/sbin/visudo -cf %s
