# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  # create wevserver VM
  config.vm.define "centos-webserver" do |webserver|
    webserver.vm.box = "sbeliakou/centos"
    webserver.vm.box_check_update = false
    webserver.vm.network :private_network, ip: "178.65.11.5"
    webserver.ssh.insert_key = false
    webserver.vm.hostname = "centos-webserver"

    webserver.vm.provider "virtualbox" do |vb|
      vb.name = "centos-webserver"
      vb.memory = "1024"
    end
  end

  # create appserver VM
  config.vm.define "centos-appserver" do |appserver|
    appserver.vm.box = "sbeliakou/centos"
    appserver.vm.box_check_update = false
    appserver.vm.network :private_network, ip: "178.65.11.6"
    appserver.ssh.insert_key = false
    appserver.vm.hostname = "centos-appserver"

    appserver.vm.provider "virtualbox" do |vb|
      vb.name = "centos-appserver"
      vb.memory = "2048"
    end
  end

end
