- hosts: localhost

  tasks:
  - name: Destroy containers
    docker_container:
      name: "{{ hostvars[item].ansible_host[0:] }}"
      state: absent
    loop: "{{ groups['webservers'] + groups['appservers'] }}"