- name: User group create
  group:
    name: "{{ user_group1 }}"
    gid: "{{ user_gid }}"
    state: present

- name: User create
  user:
    name: "{{ item.name | string}}"
    uid: "{{ item.uid | int }}"
    groups: "{{ item.groups | string }}"
    create_home: "{{ item.home| bool }}"
    state: present
  with_items:
     - { name: "{{ user_name }}", uid: "{{ user_uid }}", groups: "{{ user_group1 }}, {{ user_group2 | default(wheel) }}", 
     home: "{{ user_home }}" }

- name: User key
  authorized_key: 
    user: "{{ user_name }}"
    key: "{{ lookup('file', item | string) }}"
  with_fileglob:
    - "{{ user_key }}"

- name: User access
  copy:
    dest: "/etc/sudoers.d/{{ user_name }}"
    content: "{{ user_privs }}"